# Generated by Django 3.0.6 on 2020-05-14 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(help_text='Введите название жанра фильма (боевик, вестерн, драма и т.д.)', max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='mk_event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Идентификатор фильма')),
                ('name', models.CharField(help_text='Название мероприятия', max_length=10, verbose_name='Название мероприятия')),
                ('title', models.CharField(help_text='Введите название мероприятия', max_length=100, verbose_name='Название на сайте')),
                ('event_date', models.DateField(blank=True, help_text='Введите запланированную дату проведения мероприятия', null=True, verbose_name='Дата проведения мероприятия')),
                ('event_place', models.CharField(blank=True, help_text='Введите месот, где будет проведено мероприятие', max_length=100, null=True, verbose_name='Место проведения меропритиятия')),
                ('date', models.DateField(blank=True, help_text='Введите дату проведения мероприятия', null=True, verbose_name='Дата проведения мероаприятия')),
                ('start_time', models.TimeField(blank=True, help_text='Введите время начала мероприятия', null=True, verbose_name='Время начала мероаприятия')),
                ('description', models.TextField(blank=True, help_text='Введите описание мероприятия', max_length=600, null=True, verbose_name='Описание мероприятия')),
                ('short_description', models.TextField(blank=True, help_text='Введите краткое описание, которое будет отображаться в блоке Премьера и Постере мероприятия', max_length=100, null=True, verbose_name='Краткое описание мероприятия')),
                ('in_premiere', models.CharField(choices=[('Да', 'Отобразить в блоке'), ('Нет', 'Не отображать в блоке')], default='Нет', max_length=3, verbose_name='Отображать ли фильм в блоке "Премьеры"')),
            ],
            options={
                'ordering': ['event_id'],
            },
        ),
        migrations.CreateModel(
            name='mk_film',
            fields=[
                ('film_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Идентификатор фильма')),
                ('creation_date', models.DateTimeField(auto_now=True, verbose_name='Дата создания записи')),
                ('last_change_date', models.DateTimeField(auto_now=True, verbose_name='Дата и время последнего изменения записи')),
                ('on_screen_till', models.DateField(default='13.05.2020', verbose_name='Дата снятия с проката')),
                ('priority_mark', models.CharField(blank=True, choices=[(0, 'Обычный'), (1, 'Высокий'), (2, 'Наивысший')], default=0, max_length=1)),
                ('name', models.CharField(blank=True, help_text='Введите название фильма', max_length=50, verbose_name='Название фильма')),
            ],
            options={
                'ordering': ['film_id'],
            },
        ),
    ]
