# Generated by Django 3.0.6 on 2020-05-14 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mk_film',
            name='priority_mark',
            field=models.CharField(choices=[('О', 'Обычный'), ('В', 'Высокий'), ('Н', 'Наивысший')], default='О', max_length=1, verbose_name='Метка приоритета'),
        ),
    ]
