# Generated by Django 3.0.6 on 2020-05-14 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20200514_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='mk_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=3000, null=True, verbose_name='О нас')),
                ('manual', models.TextField(blank=True, help_text='Введите имена руководителей через запятую с пробелом', max_length=600, null=True, verbose_name='Руководство')),
                ('about_union', models.TextField(blank=True, help_text='Введите информацию профсоюз', max_length=3000, null=True, verbose_name='О профсоюзе')),
                ('documentation', models.CharField(blank=True, help_text='Введите ссылки на документы через запятую с пробелами', max_length=500, null=True, verbose_name='Ссылки на документацию')),
                ('last_change_date', models.DateTimeField(auto_now=True, verbose_name='Дата и время последнего изменения данных')),
                ('changer_name', models.CharField(max_length=100, verbose_name='Имя последнего редактора')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('ID', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateField(auto_now=True, verbose_name='Дата создания')),
                ('creater_name', models.CharField(max_length=100, verbose_name='Имя разместившего')),
                ('date_change', models.DateField(auto_now_add=True, verbose_name='Дата последнего изменения')),
                ('changer_name', models.CharField(max_length=100, verbose_name='Имя последнего редактора')),
                ('date_close', models.DateField(blank=True, null=True, verbose_name='Дата закрытия премьеры')),
                ('title', models.CharField(help_text='Введите заголовок новости', max_length=100, verbose_name='Заголовок новости')),
                ('lead', models.CharField(help_text='Введите лид новости', max_length=100, verbose_name='Лид новости')),
                ('description', models.TextField(blank=True, help_text='Введите текст новости', max_length=600, null=True, verbose_name='Новость')),
                ('source', models.CharField(blank=True, max_length=300, null=True, verbose_name='Источник')),
                ('news_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Тип новости')),
            ],
        ),
        migrations.AddField(
            model_name='mk_film',
            name='short_description',
            field=models.TextField(blank=True, help_text='Введите краткое описание фильма', max_length=500, null=True, verbose_name='Краткое описание фильма'),
        ),
        migrations.AddField(
            model_name='mk_film',
            name='title',
            field=models.CharField(blank=True, help_text='Введите название фильма', max_length=100, null=True, verbose_name='Название фильма на главной странице сайта'),
        ),
        migrations.AlterField(
            model_name='mk_film',
            name='on_screen_till',
            field=models.DateField(auto_now=True, verbose_name='Дата снятия с проката'),
        ),
        migrations.AlterField(
            model_name='mk_film',
            name='priority_mark',
            field=models.CharField(blank=True, choices=[('О', 'Обычный'), ('В', 'Высокий'), ('Н', 'Наивысший')], default='О', max_length=1, verbose_name='Метка приоритета'),
        ),
    ]
