# Generated by Django 3.0.6 on 2020-05-14 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20200514_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mk_film',
            name='on_screen_till',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата снятия с проката'),
        ),
    ]
