# Generated by Django 3.0.6 on 2020-05-14 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20200514_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mk_film',
            name='on_screen_till',
            field=models.DateField(blank=True, default='2020-05-13', null=True, verbose_name='Дата снятия с проката'),
        ),
    ]
