# Generated by Django 3.0.6 on 2020-05-14 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20200514_1326'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.DeleteModel(
            name='mk_event',
        ),
        migrations.DeleteModel(
            name='mk_film',
        ),
    ]
