# Generated by Django 3.0.5 on 2020-04-08 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('film_name', models.CharField(help_text='Введите название фильма', max_length=100, primary_key=True, serialize=False, verbose_name='Название фильма')),
                ('film_producer', models.CharField(blank=True, help_text='Введите имя режиссёра', max_length=100, null=True, verbose_name='Режиссёр')),
                ('film_country', models.CharField(blank=True, help_text='Введите страну производства фильма', max_length=100, verbose_name='Страна производства фильма')),
                ('date_of_release', models.DateField(blank=True, help_text='Введите год релиза фильма', null=True, verbose_name='Год релиза')),
                ('film_description', models.TextField(blank=True, help_text='Введите описание фильма', max_length=600, null=True, verbose_name='Описание фильма')),
            ],
            options={
                'ordering': ['-film_name'],
            },
        ),
    ]
